name: 'Braze Publish'
description: 'Publish files to Braze as a content block'
author: 'Adam Kazai'
branding:
    icon: 'upload'
    color: 'blue'

# Define your inputs here.
inputs:
    BRAZE_CONTENT_BLOCK_PREFIX:
        description: 'The prefix for the content block name'
        required: false
        default: ''
    LOG_LEVEL:
        description: 'Log level when running the action'
        required: false
    DEPLOYMENT_MODE:
        description: 'Deployment mode: init or update'
        required: false
        default: 'update'
    GITHUB_TOKEN:
        description: 'GitHub Token'
        required: true
    BRAZE_REST_ENDPOINT:
        description: 'Braze REST Endpoint'
        required: true
    BRAZE_API_KEY:
        description: 'Braze API Key'
        required: true

runs:
    using: node20
    main: dist/index.js
