name: 'Braze Publish'
description: 'Publish files to Braze as a content block'
author: 'Adam Kazai'
icon: 'upload'
color: 'blue'

# Define your inputs here.
inputs:
    GITHUB_TOKEN:
        description: 'GitHub Token'
        required: true
    BRAZE_REST_ENDPOINT:
        description: 'Braze REST Endpoint'
        required: true
    BRAZE_API_KEY:
        description: 'Braze API Key'
        required: true

runs:
    using: node20
    main: dist/index.js
